### ISSUE TITLE
DEPLOYMENT

### ISSUE THREAD

**Issue by shirleyama** [stansaner/spotify-search#44]
DEPLOYMENT
## User Story 

AS A music lover with a busy schedule
I WANT to see the top tracks and info about any artist
SO THAT I can keep informed.

## Acceptance Criteria
GIVEN the codebase follows accessibility standards
AND GitHub repository contains application code
WHEN a search engine trawls the website
THEN Application deployed at live URL.
AND Application loads with no errors.
AND Application GitHub URL submitted.

**Comment by TamzinC** [comment]
GIVEN the codebase follows accessibility standards
AND GitHub repository contains application code
WHEN a search engine trawls the website
THEN Application deployed at live URL.
AND Application loads with no errors.
AND Application GitHub URL submitted.
